import angular from 'angular';
import 'angular-animate';
import 'angular-ui-bootstrap';
import 'angular-ui-router';
import 'angular-moment';

// Import our app config files
import constants from './kobra.constants';
import appConfig from './kobra.config';
import appRun from './kobra.run';

// Import our templates file (generated by Gulp)
import './kobra.templates';
// Import our app functionaity
import './auth';
import './common';
import './components';
import './home';
import './layout';
import './lookup';

// Create and bootstrap application
const requires = [
  'ngAnimate',
  'ui.router',
  'ui.bootstrap',
  'angularMoment',
  'kobra.auth',
  'kobra.common',
  'kobra.components',
  'kobra.home',
  'kobra.layout',
  'kobra.lookup',
  'kobra.templates'
];

// Mount on window for testing
window.app = angular.module('kobra', requires);
angular.module('kobra').constant('AppConstants', constants);
angular.module('kobra').config(appConfig);
angular.module('kobra').run(appRun);
angular.bootstrap(document, ['kobra'], {
  strictDi: true
});
