# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobra', '0002_initial_unions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
