# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 01:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import kobra.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('kobra', '0002_initial_unions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [['view_user', 'Can view user']]},
        ),
    ]
