# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kobra', '0003_auto_20161109_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name'], 'permissions': [['view_event', 'Can view event']]},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'permissions': [['view_organization', 'Can view organization']]},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['liu_id'], 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['name'], 'permissions': [['view_tickettype', 'Can view ticket type']]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'permissions': [['view_user', 'Can view user']]},
        ),
        migrations.AlterField(
            model_name='discountregistration',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='organizations_administered', to=settings.AUTH_USER_MODEL),
        ),
    ]
