# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 22:09
from __future__ import unicode_literals

from django.db import migrations
import kobra.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('kobra', '0004_auto_20170116_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=kobra.db_fields.NameField(default='', max_length=64, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=kobra.db_fields.NameField(default='', max_length=64, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=kobra.db_fields.NameField(max_length=128, verbose_name='full name'),
        ),
    ]
