# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobra', '0005_auto_20170521_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mifare_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Mifare ID'),
        ),
    ]
