# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 20:51
from __future__ import unicode_literals

from django.db import migrations
import kobra.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('kobra', '0006_auto_20180111_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=kobra.db_fields.MoneyField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
