<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="StudentService"
                  targetNamespace="http://service.integration.it.liu.se/StudentService/2.0"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
                  xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
                  xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
                  xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:tns="http://service.integration.it.liu.se/StudentService/2.0"
                  xmlns:wsa10="http://www.w3.org/2005/08/addressing"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing">
  <wsp:Policy wsu:Id="WSHttpBinding_IStudentService_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <http:NegotiateAuthentication
            xmlns:http="http://schemas.microsoft.com/ws/06/2004/policy/http"/>
        <sp:TransportBinding
            xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <sp:HttpsToken RequireClientCertificate="false"/>
              </wsp:Policy>
            </sp:TransportToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256/>
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict/>
              </wsp:Policy>
            </sp:Layout>
          </wsp:Policy>
        </sp:TransportBinding>
        <wsaw:UsingAddressing/>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="BasicHttpBinding_IStudentService_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:TransportBinding
            xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <sp:HttpsToken RequireClientCertificate="false"/>
              </wsp:Policy>
            </sp:TransportToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256/>
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Lax/>
              </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp/>
          </wsp:Policy>
        </sp:TransportBinding>
        <sp:SignedSupportingTokens
            xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:UsernameToken
                sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
              <wsp:Policy>
                <sp:WssUsernameToken10/>
              </wsp:Policy>
            </sp:UsernameToken>
          </wsp:Policy>
        </sp:SignedSupportingTokens>
        <sp:Wss10
            xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy/>
        </sp:Wss10>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xs:schema elementFormDefault="qualified"
               targetNamespace="http://service.integration.it.liu.se/StudentService/2.0"
               xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import
          namespace="http://service.integration.it.liu.se/EmployeeService/2.1/Contract"/>
      <xs:element name="IsStudent">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="IsStudent" nillable="true"
                        type="q1:IsStudentRequest"
                        xmlns:q1="http://service.integration.it.liu.se/EmployeeService/2.1/Contract"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="IsStudentResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="IsStudentResult" type="xs:boolean"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetStudent">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="Request" nillable="true"
                        type="q2:GetStudentRequest"
                        xmlns:q2="http://service.integration.it.liu.se/EmployeeService/2.1/Contract"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetStudentResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetStudentResult" nillable="true"
                        type="q3:GetStudentResponse"
                        xmlns:q3="http://service.integration.it.liu.se/EmployeeService/2.1/Contract"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetStudentExtended">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="Request" nillable="true"
                        type="q4:GetStudentExtendedRequest"
                        xmlns:q4="http://service.integration.it.liu.se/EmployeeService/2.1/Contract"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetStudentExtendedResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetStudentExtendedResult"
                        nillable="true" type="q5:GetStudentExtendedResponse"
                        xmlns:q5="http://service.integration.it.liu.se/EmployeeService/2.1/Contract"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ListStudents">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="ListStudentsResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="ListStudentsResult" nillable="true"
                        type="q6:ListStudentsResponse"
                        xmlns:q6="http://service.integration.it.liu.se/EmployeeService/2.1/Contract"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified"
               targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/"
               xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:element name="anyType" nillable="true" type="xs:anyType"/>
      <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
      <xs:element name="boolean" nillable="true" type="xs:boolean"/>
      <xs:element name="byte" nillable="true" type="xs:byte"/>
      <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
      <xs:element name="decimal" nillable="true" type="xs:decimal"/>
      <xs:element name="double" nillable="true" type="xs:double"/>
      <xs:element name="float" nillable="true" type="xs:float"/>
      <xs:element name="int" nillable="true" type="xs:int"/>
      <xs:element name="long" nillable="true" type="xs:long"/>
      <xs:element name="QName" nillable="true" type="xs:QName"/>
      <xs:element name="short" nillable="true" type="xs:short"/>
      <xs:element name="string" nillable="true" type="xs:string"/>
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
      <xs:element name="char" nillable="true" type="tns:char"/>
      <xs:simpleType name="char">
        <xs:restriction base="xs:int"/>
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration"/>
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid"/>
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern
              value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName"/>
      <xs:attribute name="Id" type="xs:ID"/>
      <xs:attribute name="Ref" type="xs:IDREF"/>
    </xs:schema>
    <xs:schema elementFormDefault="qualified"
               targetNamespace="http://service.integration.it.liu.se/EmployeeService/2.1/Contract"
               xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns:tns="http://service.integration.it.liu.se/EmployeeService/2.1/Contract">
      <xs:import namespace="http://service.integration.it.liu.se/ViewModels"/>
      <xs:import
          namespace="http://service.integration.it.liu.se/EmployeeService/2.1/ViewModels"/>
      <xs:complexType name="IsStudentRequest">
        <xs:sequence>
          <xs:element name="Identity" nillable="true" type="q1:Identity"
                      xmlns:q1="http://service.integration.it.liu.se/ViewModels"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="IsStudentRequest" nillable="true"
                  type="tns:IsStudentRequest"/>
      <xs:complexType name="GetStudentRequest">
        <xs:sequence>
          <xs:element name="Identity" nillable="true" type="q2:Identity"
                      xmlns:q2="http://service.integration.it.liu.se/ViewModels"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="GetStudentRequest" nillable="true"
                  type="tns:GetStudentRequest"/>
      <xs:complexType name="GetStudentResponse">
        <xs:sequence>
          <xs:element name="Student" nillable="true" type="q3:Student"
                      xmlns:q3="http://service.integration.it.liu.se/EmployeeService/2.1/ViewModels"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="GetStudentResponse" nillable="true"
                  type="tns:GetStudentResponse"/>
      <xs:complexType name="GetStudentExtendedRequest">
        <xs:sequence>
          <xs:element name="Identity" nillable="true" type="q4:Identity"
                      xmlns:q4="http://service.integration.it.liu.se/ViewModels"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="GetStudentExtendedRequest" nillable="true"
                  type="tns:GetStudentExtendedRequest"/>
      <xs:complexType name="GetStudentExtendedResponse">
        <xs:sequence>
          <xs:element name="CampusCard" nillable="true" type="q5:CampusCard"
                      xmlns:q5="http://service.integration.it.liu.se/EmployeeService/2.1/ViewModels"/>
          <xs:element name="CourseRegistrations" nillable="true"
                      type="q6:ArrayOfCourseRegistration"
                      xmlns:q6="http://service.integration.it.liu.se/EmployeeService/2.1/ViewModels"/>
          <xs:element name="ProgramRegistrations" nillable="true"
                      type="q7:ArrayOfProgramRegistration"
                      xmlns:q7="http://service.integration.it.liu.se/EmployeeService/2.1/ViewModels"/>
          <xs:element name="Student" nillable="true" type="q8:StudentExtended"
                      xmlns:q8="http://service.integration.it.liu.se/EmployeeService/2.1/ViewModels"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="GetStudentExtendedResponse" nillable="true"
                  type="tns:GetStudentExtendedResponse"/>
      <xs:complexType name="ListStudentsResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="Students" nillable="true"
                      type="q9:ArrayOfListIdentity"
                      xmlns:q9="http://service.integration.it.liu.se/ViewModels"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ListStudentsResponse" nillable="true"
                  type="tns:ListStudentsResponse"/>
    </xs:schema>
    <xs:schema elementFormDefault="qualified"
               targetNamespace="http://service.integration.it.liu.se/ViewModels"
               xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns:tns="http://service.integration.it.liu.se/ViewModels">
      <xs:complexType name="Identity">
        <xs:sequence>
          <xs:element minOccurs="0" name="IsoNumber" nillable="true"
                      type="xs:string"/>
          <xs:element minOccurs="0" name="LiUId" nillable="true"
                      type="xs:string"/>
          <xs:element minOccurs="0" name="MifareNumber" nillable="true"
                      type="xs:string"/>
          <xs:element minOccurs="0" name="norEduPersonLIN" nillable="true"
                      type="xs:string"/>
          <xs:element minOccurs="0" name="norEduPersonNIN" nillable="true"
                      type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="Identity" nillable="true" type="tns:Identity"/>
      <xs:complexType name="ArrayOfListIdentity">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="ListIdentity"
                      nillable="true" type="tns:ListIdentity"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfListIdentity" nillable="true"
                  type="tns:ArrayOfListIdentity"/>
      <xs:complexType name="ListIdentity">
        <xs:sequence>
          <xs:element name="LiUId" nillable="true" type="xs:string"/>
          <xs:element name="norEduPersonLIN" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ListIdentity" nillable="true" type="tns:ListIdentity"/>
    </xs:schema>
    <xs:schema elementFormDefault="qualified"
               targetNamespace="http://service.integration.it.liu.se/EmployeeService/2.1/ViewModels"
               xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns:tns="http://service.integration.it.liu.se/EmployeeService/2.1/ViewModels">
      <xs:import
          namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
      <xs:complexType name="Student">
        <xs:sequence>
          <xs:element name="DisplayName" nillable="true" type="xs:string"/>
          <xs:element name="EmailAddress" nillable="true" type="xs:string"/>
          <xs:element name="GivenName" nillable="true" type="xs:string"/>
          <xs:element name="LiUId" nillable="true" type="xs:string"/>
          <xs:element name="LiULIN" nillable="true" type="xs:string"/>
          <xs:element name="MainUnion" nillable="true" type="xs:string"/>
          <xs:element name="StudentUnion" nillable="true" type="xs:string"/>
          <xs:element name="SurName" nillable="true" type="xs:string"/>
          <xs:element name="eduPersonAffiliations" nillable="true"
                      type="q1:ArrayOfstring"
                      xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
          <xs:element name="eduPersonPrimaryAffiliation" nillable="true"
                      type="xs:string"/>
          <xs:element name="eduPersonScopedAffiliations" nillable="true"
                      type="q2:ArrayOfstring"
                      xmlns:q2="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
          <xs:element name="norEduPersonLIN" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="Student" nillable="true" type="tns:Student"/>
      <xs:complexType name="CampusCard">
        <xs:sequence>
          <xs:element name="CardId" nillable="true" type="xs:string"/>
          <xs:element name="CardStatus" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="CampusCard" nillable="true" type="tns:CampusCard"/>
      <xs:complexType name="ArrayOfCourseRegistration">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded"
                      name="CourseRegistration" nillable="true"
                      type="tns:CourseRegistration"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfCourseRegistration" nillable="true"
                  type="tns:ArrayOfCourseRegistration"/>
      <xs:complexType name="CourseRegistration">
        <xs:sequence>
          <xs:element name="CourseCode" nillable="true" type="xs:string"/>
          <xs:element name="CourseMomentCode" nillable="true" type="xs:string"/>
          <xs:element name="CourseOfferingKey" nillable="true"
                      type="xs:string"/>
          <xs:element name="DescriptionEn" nillable="true" type="xs:string"/>
          <xs:element name="DescriptionSv" nillable="true" type="xs:string"/>
          <xs:element name="EndWeek" nillable="true" type="xs:int"/>
          <xs:element name="Form" nillable="true" type="xs:string"/>
          <xs:element name="Location" nillable="true" type="xs:string"/>
          <xs:element name="Pace" nillable="true" type="xs:int"/>
          <xs:element name="Semester" type="xs:int"/>
          <xs:element name="SemesterOrder" nillable="true" type="xs:int"/>
          <xs:element name="Set" nillable="true" type="xs:string"/>
          <xs:element name="StartWeek" nillable="true" type="xs:int"/>
          <xs:element name="TitleEn" nillable="true" type="xs:string"/>
          <xs:element name="TitleSv" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="CourseRegistration" nillable="true"
                  type="tns:CourseRegistration"/>
      <xs:complexType name="ArrayOfProgramRegistration">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded"
                      name="ProgramRegistration" nillable="true"
                      type="tns:ProgramRegistration"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfProgramRegistration" nillable="true"
                  type="tns:ArrayOfProgramRegistration"/>
      <xs:complexType name="ProgramRegistration">
        <xs:sequence>
          <xs:element name="Location" nillable="true" type="xs:string"/>
          <xs:element name="ProgramCode" nillable="true" type="xs:string"/>
          <xs:element name="Semester" nillable="true" type="xs:int"/>
          <xs:element name="SemesterOrder" nillable="true" type="xs:int"/>
          <xs:element name="TitleEn" nillable="true" type="xs:string"/>
          <xs:element name="TitleSv" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ProgramRegistration" nillable="true"
                  type="tns:ProgramRegistration"/>
      <xs:complexType name="StudentExtended">
        <xs:sequence>
          <xs:element name="DisplayName" nillable="true" type="xs:string"/>
          <xs:element name="EmailAddress" nillable="true" type="xs:string"/>
          <xs:element name="GivenName" nillable="true" type="xs:string"/>
          <xs:element name="LiUId" nillable="true" type="xs:string"/>
          <xs:element name="LiULIN" nillable="true" type="xs:string"/>
          <xs:element name="MainUnion" nillable="true" type="xs:string"/>
          <xs:element name="StudentUnion" nillable="true" type="xs:string"/>
          <xs:element name="SurName" nillable="true" type="xs:string"/>
          <xs:element name="eduPersonAffiliations" nillable="true"
                      type="q3:ArrayOfstring"
                      xmlns:q3="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
          <xs:element name="eduPersonPrimaryAffiliation" nillable="true"
                      type="xs:string"/>
          <xs:element name="eduPersonScopedAffiliations" nillable="true"
                      type="q4:ArrayOfstring"
                      xmlns:q4="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
          <xs:element name="norEduPersonLIN" nillable="true" type="xs:string"/>
          <xs:element name="norEduPersonNIN" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="StudentExtended" nillable="true"
                  type="tns:StudentExtended"/>
    </xs:schema>
    <xs:schema elementFormDefault="qualified"
               targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"
               xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
      <xs:complexType name="ArrayOfstring">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="string"
                      nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfstring" nillable="true"
                  type="tns:ArrayOfstring"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IStudentService_IsStudent_InputMessage">
    <wsdl:part name="parameters" element="tns:IsStudent"/>
  </wsdl:message>
  <wsdl:message name="IStudentService_IsStudent_OutputMessage">
    <wsdl:part name="parameters" element="tns:IsStudentResponse"/>
  </wsdl:message>
  <wsdl:message name="IStudentService_GetStudent_InputMessage">
    <wsdl:part name="parameters" element="tns:GetStudent"/>
  </wsdl:message>
  <wsdl:message name="IStudentService_GetStudent_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetStudentResponse"/>
  </wsdl:message>
  <wsdl:message name="IStudentService_GetStudentExtended_InputMessage">
    <wsdl:part name="parameters" element="tns:GetStudentExtended"/>
  </wsdl:message>
  <wsdl:message name="IStudentService_GetStudentExtended_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetStudentExtendedResponse"/>
  </wsdl:message>
  <wsdl:message name="IStudentService_ListStudents_InputMessage">
    <wsdl:part name="parameters" element="tns:ListStudents"/>
  </wsdl:message>
  <wsdl:message name="IStudentService_ListStudents_OutputMessage">
    <wsdl:part name="parameters" element="tns:ListStudentsResponse"/>
  </wsdl:message>
  <wsdl:portType name="IStudentService">
    <wsdl:operation name="IsStudent">
      <wsdl:input
          wsaw:Action="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/IsStudent"
          message="tns:IStudentService_IsStudent_InputMessage"/>
      <wsdl:output
          wsaw:Action="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/IsStudentResponse"
          message="tns:IStudentService_IsStudent_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetStudent">
      <wsdl:input
          wsaw:Action="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/GetStudent"
          message="tns:IStudentService_GetStudent_InputMessage"/>
      <wsdl:output
          wsaw:Action="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/GetStudentResponse"
          message="tns:IStudentService_GetStudent_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetStudentExtended">
      <wsdl:input
          wsaw:Action="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/GetStudentExtended"
          message="tns:IStudentService_GetStudentExtended_InputMessage"/>
      <wsdl:output
          wsaw:Action="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/GetStudentExtendedResponse"
          message="tns:IStudentService_GetStudentExtended_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="ListStudents">
      <wsdl:input
          wsaw:Action="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/ListStudents"
          message="tns:IStudentService_ListStudents_InputMessage"/>
      <wsdl:output
          wsaw:Action="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/ListStudentsResponse"
          message="tns:IStudentService_ListStudents_OutputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WSHttpBinding_IStudentService" type="tns:IStudentService">
    <wsp:PolicyReference URI="#WSHttpBinding_IStudentService_policy"/>
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="IsStudent">
      <soap12:operation
          soapAction="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/IsStudent"
          style="document"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetStudent">
      <soap12:operation
          soapAction="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/GetStudent"
          style="document"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetStudentExtended">
      <soap12:operation
          soapAction="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/GetStudentExtended"
          style="document"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ListStudents">
      <soap12:operation
          soapAction="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/ListStudents"
          style="document"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="BasicHttpBinding_IStudentService"
                type="tns:IStudentService">
    <wsp:PolicyReference URI="#BasicHttpBinding_IStudentService_policy"/>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="IsStudent">
      <soap:operation
          soapAction="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/IsStudent"
          style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetStudent">
      <soap:operation
          soapAction="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/GetStudent"
          style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetStudentExtended">
      <soap:operation
          soapAction="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/GetStudentExtended"
          style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ListStudents">
      <soap:operation
          soapAction="http://service.integration.it.liu.se/StudentService/2.0/IStudentService/ListStudents"
          style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="StudentService">
    <wsdl:port name="WSHttpBinding_IStudentService"
               binding="tns:WSHttpBinding_IStudentService">
      <soap12:address
          location="https://service.integration.it.liu.se/StudentService/2.0/StudentService.svc"/>
      <wsa10:EndpointReference>
        <wsa10:Address>
          https://service.integration.it.liu.se/StudentService/2.0/StudentService.svc
        </wsa10:Address>
        <Identity
            xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
          <Upn>sesam_external_srv@ad.liu.se</Upn>
        </Identity>
      </wsa10:EndpointReference>
    </wsdl:port>
    <wsdl:port name="BasicHttpBinding_IStudentService"
               binding="tns:BasicHttpBinding_IStudentService">
      <soap:address
          location="https://service.integration.it.liu.se/StudentService/2.0/StudentService.svc/basic"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
